### PR TITLE
Add drive screen

### PR DESCRIPTION
**Pull request by DSIW**
Screenshot_1713024635
Screenshot_1713024638

### CODE REVIEW

**Comment by TheFreal** [comment]
A more fully featured driving mode that automatically engages when the scooter is in drive gear is on the roadmap. Something roughly like this:
Driving mode sketch

**Comment by DSIW** [comment]
Love the mock up! 😍

Should I stop with this screen or do we want to evolve it in iterations? E.g. I could fix the merge conflicts. Wdyt?

**Comment by TheFreal** [comment]
I'll probably reimplement it when the time comes, so you can close this PR if that's okay with you?

**Comment by DSIW** [comment]
Alright! Will keep it in a local branch for myself then

**Pull request closed without merging**
