### PR TITLE
renamed Batt_50.webp to batt_50.webp, on linux (case sensitive)

### PR DESCRIPTION
**Pull request by hu8813**
Feature summary

## QA checklist

- [ ] Read state (state & power state)
- [ ] Read primary battery SOC
- [ ] Read primary battery cycles
- [ ] Read secondary battery SOC
- [ ] Read secondary battery cycles
- [ ] Read seat closed
- [ ] Read handlebar
- [ ] Read AUX SOC
- [ ] Read CBB SOC
- [ ] Read CBB charging state
- [ ] Update ping
- [ ] SOCs are cached (after app restart)
- [ ] Commands can be sent (locking & hibernation)

### CODE REVIEW

**Comment by TheFreal** [comment]
Thanks for the great PR and welcome to the project! Are the new languages machine-translated or by speakers of those languages?

**Comment by hu8813** [comment]
Hi. Thanks. I'm beginner in flutter, that was what I could do. Unfortunately machine translation via openai gpt.

**Comment by TheFreal** [comment]
Hmm, could we split this into two PRs then? I want to merge the naming fix right away, but it might be better to have some native speakers look at the translations first.

**Comment by hu8813** [comment]
sure. let me check how to do that

**Pull request closed without merging**
