### PR TITLE
chore: install as separate debug app

### PR DESCRIPTION
**Pull request by DSIW**
Feature summary

## QA checklist

- [ ] Read state (state & power state)
- [ ] Read primary battery SOC
- [ ] Read primary battery cycles
- [ ] Read secondary battery SOC
- [ ] Read secondary battery cycles
- [ ] Read seat closed
- [ ] Read handlebar
- [ ] Read AUX SOC
- [ ] Read CBB SOC
- [ ] Read CBB charging state
- [ ] Update ping
- [ ] SOCs are cached (after app restart)
- [ ] Commands can be sent (locking & hibernation)

### CODE REVIEW

**Comment by TheFreal** [comment]
This doesn't need the scripts folder, right?

**Comment by DSIW** [comment]
Correct, is more a helper for myself. Do you have a better place in mind?

E.g. in NPM I would've used the package.json run scripts section.

**Comment by TheFreal** [comment]
I use the launch.json in the .vscode folder, which is already gitignored.
I propose we also exclude the script folder from versioning entirely.

**Comment by TheFreal** [comment]
Merged for now because this is a really good improvement and I want it on main as quickly as possible 😄

**Pull request merged**
